package model.services;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import model.services.common.AppModule;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 25 10:49:02 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for XxOdmIssueToFinishDTVO1.
     * @return XxOdmIssueToFinishDTVO1
     */
    public ViewObjectImpl getXxOdmIssueToFinishDTVO1() {
        return (ViewObjectImpl)findViewObject("XxOdmIssueToFinishDTVO1");
    }

    /**
     * Container's getter for XxOdmIssueToFinishHTVO1.
     * @return XxOdmIssueToFinishHTVO1
     */
    public ViewObjectImpl getXxOdmIssueToFinishHTVO1() {
        return (ViewObjectImpl)findViewObject("XxOdmIssueToFinishHTVO1");
    }

    /**
     * Container's getter for XxOdmIssueToFinishLTVO1.
     * @return XxOdmIssueToFinishLTVO1
     */
    public ViewObjectImpl getXxOdmIssueToFinishLTVO1() {
        return (ViewObjectImpl)findViewObject("XxOdmIssueToFinishLTVO1");
    }

    /**
     * Container's getter for XxOdmIssueToFinishDTVO2.
     * @return XxOdmIssueToFinishDTVO2
     */
    public ViewObjectImpl getXxOdmIssueToFinishDTVO2() {
        return (ViewObjectImpl)findViewObject("XxOdmIssueToFinishDTVO2");
    }

    /**
     * Container's getter for XxOdmIssueToFinishLTVO2.
     * @return XxOdmIssueToFinishLTVO2
     */
    public ViewObjectImpl getXxOdmIssueToFinishLTVO2() {
        return (ViewObjectImpl)findViewObject("XxOdmIssueToFinishLTVO2");
    }

    /**
     * Container's getter for XxOdmIsuueToFinishDFkLink1.
     * @return XxOdmIsuueToFinishDFkLink1
     */
    public ViewLinkImpl getXxOdmIsuueToFinishDFkLink1() {
        return (ViewLinkImpl)findViewLink("XxOdmIsuueToFinishDFkLink1");
    }

    /**
     * Container's getter for XxOdmIsuueToFinishLUkLink1.
     * @return XxOdmIsuueToFinishLUkLink1
     */
    public ViewLinkImpl getXxOdmIsuueToFinishLUkLink1() {
        return (ViewLinkImpl)findViewLink("XxOdmIsuueToFinishLUkLink1");
    }
    
    public void setSessionValues(String orgId, String userId, String respId,
                                         String respAppl) {
          
                

                if (userId != null) {
                   // String flag = getFlagValue(userId, respId);
                    FacesContext fctx = FacesContext.getCurrentInstance();
                    ExternalContext ectx = fctx.getExternalContext();
                    HttpSession userSession = (HttpSession)ectx.getSession(false);
                  //  userSession.setAttribute("Flag", flag);
                    userSession.setAttribute("userId", userId);
                    userSession.setAttribute("orgId", orgId);
                    userSession.setAttribute("respId", respId);
                    userSession.setAttribute("unitName", getUnitName(orgId));
                }
            }


    /**
     * Container's getter for OrgNameLov1.
     * @return OrgNameLov1
     */
    public ViewObjectImpl getOrgNameLov1() {
        return (ViewObjectImpl)findViewObject("OrgNameLov1");
    }
    
    

    public String getUnitName (String orgId){
        
        ViewObject vo = getOrgNameLov1();
        vo.setWhereClause("ORGANIZATION_ID = "+orgId);
        vo.executeQuery();
        String name = null;
        vo.first();
        
        try {
            name = vo.getCurrentRow().getAttribute("Name").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }
        return name ;
            
    }

    /**
     * Container's getter for XxOdmIssueToFinishDTVO3.
     * @return XxOdmIssueToFinishDTVO3
     */
    public ViewObjectImpl getXxOdmIssueToFinishDTVO3() {
        return (ViewObjectImpl)findViewObject("XxOdmIssueToFinishDTVO3");
    }

    /**
     * Container's getter for XxOdmIsuueToFinishDFkLink2.
     * @return XxOdmIsuueToFinishDFkLink2
     */
    public ViewLinkImpl getXxOdmIsuueToFinishDFkLink2() {
        return (ViewLinkImpl)findViewLink("XxOdmIsuueToFinishDFkLink2");
    }

    /**
     * Container's getter for fiilDataVO1.
     * @return fiilDataVO1
     */
    public ViewObjectImpl getfiilDataVO1() {
        return (ViewObjectImpl)findViewObject("fiilDataVO1");
    }

    /**
     * Container's getter for IseamSizePOPUPVO1.
     * @return IseamSizePOPUPVO1
     */
    public ViewObjectImpl getIseamSizePOPUPVO1() {
        return (ViewObjectImpl)findViewObject("IseamSizePOPUPVO1");
    }
}
